apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
  namespace: petclinic
spec:
  env:
    - name: HONEYCOMB_API_KEY                                                                                                                                                       
      valueFrom:                                                                                                                                                                    
        secretKeyRef:                                                                                                                                                               
          key: api-key                                                                                                                                                              
          name: honeycomb 
  config: |
    receivers:
      otlp:
        protocols:
          grpc: # on port 4317
          http: # on port 4318
    processors:
      batch:
    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: "api.honeycomb.io:443"
        headers:
          "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
          "x-honeycomb-dataset": "petclinic"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]